In [60]:
from datasets import load_dataset

ds = load_dataset("MakTek/Customer_support_faqs_dataset")

df = ds["train"].to_pandas()

print(df.head())

                              question  \
0         How can I create an account?
1  What payment methods do you accept?
2            How can I track my order?
3          What is your return policy?
4               Can I cancel my order?

                                              answer
0  To create an account, click on the 'Sign Up' b...
1  We accept major credit cards, debit cards, and...
2  You can track your order by logging into your ...
3  Our return policy allows you to return product...
4  You can cancel your order if it has not been s...

In [61]:
df['answer'] = df['answer'].str.replace('\n', ' ')

In [62]:
df['answer']

0      To create an account, click on the 'Sign Up' b...
1      We accept major credit cards, debit cards, and...
2      You can track your order by logging into your ...
3      Our return policy allows you to return product...
4      You can cancel your order if it has not been s...
                             ...
195    Yes, we offer a satisfaction guarantee on our ...
196    To apply for a job at our company, visit our C...
197    The warranty on our products varies by item. P...
198    If the price of a product drops within 7 days ...
199    To reset your password, click on the 'Forgot P...
Name: answer, Length: 200, dtype: str

In [63]:
df['question'] = df['question'].str.replace('\n', ' ')

In [64]:
df['question']

0                           How can I create an account?
1                    What payment methods do you accept?
2                              How can I track my order?
3                            What is your return policy?
4                                 Can I cancel my order?
                             ...
195               Do you offer a satisfaction guarantee?
196           How can I apply for a job at your company?
197               What is the warranty on your products?
198    Can I request a refund if the price drops afte...
199                         How can I reset my password?
Name: question, Length: 200, dtype: str

In [65]:
len(df)

200

In [66]:
df['combined'] = df['question'] + " " + df['answer']

In [67]:
df.drop(columns=['question', 'answer'], inplace=True)

In [68]:
df.head()

                                            combined
0  How can I create an account? To create an acco...
1  What payment methods do you accept? We accept ...
2  How can I track my order? You can track your o...
3  What is your return policy? Our return policy ...
4  Can I cancel my order? You can cancel your ord...

In [69]:
df['combined'].isnull().sum()

np.int64(0)

In [72]:
df['combined'].shape

(200,)

In [75]:
df.sample(6)

                                              combined
156  How can I apply for a job at your company? To ...
194  What are your business hours? Our business hou...
4    Can I cancel my order? You can cancel your ord...
52   Can I request a product if it is not currently...
25   Can I return a product if I changed my mind? Y...
36   Can I order a product that is listed as 'comin...

In [76]:
df['combined'][0]

"How can I create an account? To create an account, click on the 'Sign Up' button on the top right corner of our website and follow the instructions to complete the registration process."

In [79]:
df['combined'][10]

'Do you offer gift wrapping services? Yes, we offer gift wrapping services for an additional fee. During the checkout process, you can select the option to add gift wrapping to your order.'

In [81]:
df.to_csv('./DATA/customer_support_faqs_dataset.csv', index=False)

In [83]:
df1=pd.read_csv('./DATA/product_policies_10k.txt')